version: '3'
services:
  api:
    container_name: expampleappnestjs
    restart: always
    build: .
    ports:
      - '5000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mymongodatabasefornestjs
    image: mongo
    ports:
      - '27018:27017'
